# Generated by Django 4.2.6 on 2023-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_staff_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('AuthorName', models.CharField(max_length=100)),
                ('CountryName', models.CharField(max_length=100)),
            ],
        ),
    ]
