# Generated by Django 4.2.6 on 2023-11-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0004_student_models_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee_model",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="media/profile_pic"),
        ),
        migrations.AddField(
            model_name="library_model",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="media/profile_pic"),
        ),
        migrations.AddField(
            model_name="staff_model",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="media/profile_pic"),
        ),
        migrations.AddField(
            model_name="teacher_model",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="media/profile_pic"),
        ),
    ]
